```{r setting options and loading data, include=FALSE}
knitr::opts_chunk$set(echo =FALSE, message=FALSE, warning=FALSE)
# source("./GeneralFunctions.R")
# source("./AdminBoundaries.R")

load("/home/coleen/Documents/GitHub/RiXie/Data/codes_desc.RData")
load("/home/coleen/Documents/GitHub/RiXie/Data/Spotlight_data.RData")
sys.source("./GetWorldBank.R", envir = knitr::knit_global())
sys.source("./GetINFORM.R", envir = knitr::knit_global())
sys.source("./AdminBoundaries.R",envir = knitr::knit_global())
sys.source("./GeneralFunctions.R",envir = knitr::knit_global())
```


```{r selecting country}
#country select
#ountry_iso <-"SWZ"

country_full <- convIso3Country(country_iso)
pres_title <- country_full
pres_date <- Sys.Date()
```


```{r Basic Risk Data-Indices Tables}
#-------WORLD BANK------
oldnames <- c("Indicator", "Year")
newnames <- c("Index", "Year of Publication")

country_wbank <- lapply(WB_data_all, function(x) x[x$iso3 == country_iso,]) %>%
  do.call(rbind,.) %>%
  mutate(Indicator = row.names(.)) %>% 
  #plyr::join(., Rank_class_df, by="Rank_class") %>%
  dplyr::select("Indicator", "Value","Year", "Rank","Rank_out_of", "Rank_class") %>%
  arrange(Indicator) %>%
  left_join(.,Wbank_codes_desc, by = c("Indicator" = "Variable.API.Name")) %>% #add description and source
  mutate(across(everything(), as.vector)) %>% #remove any attribute label
  rename_at(vars(oldnames), ~ newnames) %>%
  mutate(URL = paste0("https://data.worldbank.org/indicator/",Index)) %>%
  mutate(Unit = str_match(Indicator.Name, "\\((.*)\\)")[,1]) %>%
  mutate(Unit  = ifelse(is.na(Unit)==TRUE, as.character("(-)"), Unit)) %>% 
  mutate(Unit = case_when(grepl("migration", Indicator.Name) ==TRUE~"(net total of migrants)",
                          grepl("Food production",Indicator.Name)==TRUE ~"(aggregate volume of agricultural production in comparison with the base period 2014-2016)",TRUE ~ Unit)) %>%
  mutate(Indicator.Name = unlist(strsplit(.$`Indicator.Name`," \\(.*\\)"))) 
  

#------INFORM-----
country_inform <- lapply(Inform_country_with_ranks, function(x) x[x$iso == country_iso,]) %>% #remove the iso column
  do.call(rbind, .) %>%
  {`[`(.[,-1])} %>% #remove column 1, which is the iso3 column
  t  %>%
  data.frame() %>%
  mutate(Index = rownames(.)) %>%
  dplyr::select(Index, Value, Rank, Rank_out_of, Rank_class) %>%
  #plyr::join(., Rank_class_df, by="Rank_class") %>%
  filter(complete.cases(.)) %>%
  left_join(.,Inform_codes_desc, by = c("Index" = "INFORM.Id")) %>% #add description and source
  mutate(Source = dataset, `Year of Publication` = inform_year) %>%
  mutate(URL = as.character("https://drmkc.jrc.ec.europa.eu/inform-index")) %>%
  mutate(Unit = as.character("(scale 0-10)"))

#-----Combine WORLDBANK and INFORM datasets-------
#function to group indicators/incides
indicator_group <-function(indicator){
 if(grepl("INFORM", indicator) == TRUE ){
   grp <- "Risk Index"
 } else if (grepl("HA|PRCP|ATM| ", indicator) == TRUE){
   grp <- "Hazard"
 } else if (grepl("RUR|FRST|POP| ", indicator) == TRUE){
   grp <- "Exposure"
 } else
   grp <- "Vulnerability"
 }
  

#Define df for matching numeric class with string class
Rank_class_df <- data.frame(Rank_class = 1:5, Class_levels = as.factor(c("Very Low","Low","Moderate","High","Very High")))
Rank_class_df$Class_levels <- factor(Rank_class_df$Class_levels ,levels = c("Very Low","Low","Moderate","High","Very High"))

#order or groupings for table:
target_grp <- c("Risk Index", "Hazard","Exposure", "Vulnerability","Others -to be classified") 

Wbank_inform_combi <- plyr::rbind.fill(country_inform, country_wbank) %>%
  plyr::join(., Rank_class_df, by="Rank_class") %>%
  #mutate(Rank = paste(Rank, Rank_out_of, sep = "/")) %>%
  dplyr::select(-Rank_class) %>%
  mutate(Description = " ") %>%
  mutate(Category = sapply(.$Index, indicator_group)) %>%
  arrange(factor(Category, levels = target_grp)) %>%
  rename_at(vars(c("Indicator.Name","Class_levels")),~ c("Index_name","Comparative Value"))
```


```{r Table Wbank_inform_combi, include=FALSE}
#--table---
library(kableExtra)
library(forcats)
source("./Spotlight_plotting_functions.R")
#---------------------------------
#Combined WBANK+INFORM table plot
#---------------------------------

#Rows from inform need indentation (sublevels)
inform_row_indent <- function(df, level){
  df %>%  
  mutate(row=row_number()) %>% 
  filter(grepl("INFORM", Source)) %>% 
  filter(str_count(Index, '\\.') == level) %>%
  dplyr::select(row) %>%
  unlist(.) %>%
  unname(.)
}

ind1 <- inform_row_indent(Wbank_inform_combi,level=1)
ind2 <-  inform_row_indent(Wbank_inform_combi,level=2)

# Wbank_inform_combi[c("Index_name","Description","Value","Year of Publication","Rank","Comparative Value","Source")] %>%
#   tibble()%>%
#   kbl(escape=F, align = 'lcccrcl') %>%
#   kable_paper("striped", full_width = T, font_size = 13) %>%
#   column_spec(c(1,2,7), width_min = c("6cm","6cm","5cm"), width_max = c("15cm","6cm","5cm")) %>%
#   pack_rows(index = table(fct_inorder(Wbank_inform_combi$Category))) %>%
#   column_spec(6, color = "white",
#               background = spec_color(as.numeric(Wbank_inform_combi$`Comparative Value`),alpha = 0.75, end = 0.4, option = "inferno")) %>%
#   add_indent(ind1, level_of_indent = 0.5) %>%
#   add_indent(ind2, level_of_indent = 1) 
```


```{r Country Stats from ADM shapefile, message=FALSE, warning=FALSE, include=FALSE}
#---------------------------------
#ADM shapefiles, group by iso3cd
#----------------------------------
#function changing rank to string:
Ranking <- function(Rank, Rank_out_of){
  if(!is.na(Rank) == TRUE){
    paste(Rank, Rank_out_of, sep = "/")
    } else {
      NA
    }
}

#Subset table
var_select <-c("Codes","Category", "Description", "Mean_Value","Unit","Year_of_Publication", "Rank", "Rank_out_of","Class_levels", "Organisation", "URL")
#Grouping names
target_adm <- c("Hazard", "Exposure", "Vulnerability", "Climate Change")

## changing headers for table:
oldnames <- c("Class_levels", "Year_of_Publication", "Mean_Value", "Organisation", "Codes", "Description")
newnames <- c("Comparative Value", "Year of Publication", "Value", "Source", "Index", "Index_name") ##it's the mean value per country but labeling as `Value` to be same as basic risk data table column names 

adm_country <- lapply(adm_ranks, function(x) t(x[x$iso == country_iso,][-1])) %>%
  lapply(., data.frame, check.names=FALSE) %>%
  do.call(cbind, .) %>%
  `colnames<-`(c("Mean_Value", "Rank", "Rank_out_of","Rank_class")) %>%
  #mutate(Rank = mapply(function(x,y) Ranking(x,y), Rank,Rank_out_of)) %>%
  mutate(Codes = rownames(.)) %>%
  dplyr::select(Codes, Mean_Value, Rank, Rank_out_of, Rank_class) %>%
  plyr::join(., Rank_class_df, by="Rank_class") %>%
  mutate(Mean_Value = round(Mean_Value,2) ) %>%
  #mutate(Rank_class  = ifelse(is.na(Rank_class)==TRUE,1,Rank_class)) %>% # to deal with NAs in Rank, for plotting later
  left_join(., adm_sources, by = c("Codes" = "GDLCODE")) %>% #add description and source
  dplyr::select(var_select) %>%
  rename_at(vars(oldnames), ~ newnames) %>%
 # mutate(Source = paste0(Source," (",URL,")" )) %>%
  arrange(factor(Category, levels = target_adm)) %>%
  filter(complete.cases(Category)) %>%
  #rmeove air pollution - duplicate with worldbank 
  filter(Index !='ArPlltn')

  
#table shapefile
adm_country[c(2,3,4,5,7,8)] %>%
   kbl(escape=F, align = 'lccccl') %>%
  kable_paper("striped", full_width = T, font_size = 13) %>%
  column_spec(c(1,6), width_min = c("8cm","5cm"), width_max = c("8cm","5cm")) %>%
  pack_rows(index = table(fct_inorder(adm_country$Category))) %>%
  column_spec(5, color = "white",
              background = spec_color(as.numeric(adm_country$`Comparative Value`),alpha = 0.75, end = 0.4, option = "inferno"))
# %>%
#   add_header_above(c("Country Statistics" = 2), font_size = "medium")
```


```{r Map design, include=FALSE}
library(ggplot2)
library(ggmap)
knitr::opts_chunk$set(dev.args=list(bg="transparent"))
theme_set(theme_bw(base_size=12)) 
theme_update(panel.background = element_rect(fill = "transparent", colour = NA),
             plot.background = element_rect(fill = "transparent", colour = NA))


bbox<-countriesbbox(country_iso)
# we want longitude to be three times wider than latitude
disty<-c(bbox[3]-bbox[1],bbox[4]-bbox[2])
if(disty[1]<3*disty[2]){
  bbox[1]<-bbox[1]+0.5*disty[1]-1.5*disty[2]
  bbox[3]<-bbox[3]-0.5*disty[1]+1.5*disty[2]
} else{
  bbox[2]<-bbox[2]+0.5*disty[2]-disty[1]/6
  bbox[4]<-bbox[4]-0.5*disty[2]+disty[1]/6
}


# Add some padding to the plot
bbox%<>%expandBbox(1.5)
mad_map <- get_stamenmap(bbox,source = "terrain-background", zoom=9)
country_gadm<-GetUNMaps(country_iso)
p <- ggmap(mad_map, maprange=FALSE) 
bg_fill<-"#f5f7fb"


```

<!--#################HTML (or pdf?) page starts here#########################-->

---
title: `r pres_title` RiX Spotlight
subtitle: "Disaster Risk Data Overview"
output:
  html_document:
      css: styles.css
---

<body style="background-color:`r bg_fill`;">

<style type="text/css">
h1.title {
  font-size: 50px;
  color:  #000000;
  text-align: center;
}
h3.subtitle {
  font-size: 30px;
  color:  #000000;
  text-align: center;
}
.table-hover > tbody > tr:hover { 
  background-color: #f7f7e6;
}
.main-container {
 zoom:70%;
  width: 80%;
    max-width:80%;
  }
</style>

```{r RiX logo}
htmltools::img(src = knitr::image_uri("/home/coleen/Documents/GRAF_files/GRAF-RIX_Map-E _tall.svg"), 
               alt = 'logo', 
               style = 'position:absolute; top:0; left:8; padding:10px;')

```

<!-- PLOTS AND TABLES from HERE: -->

<!-- <div style="float:right; position:relative; top:-150px;margin-bottom:-100px;margin-right:10px;"> -->
```{r COUNTRY MAP plot, fig.align='center',fig.width=15,fig.height=8}
library(ggspatial)
#change colors to hexa format
p + geom_sf(data=st_as_sf(country_gadm),fill="#9ABBD6", alpha=0.5, inherit.aes = FALSE) +
  xlab("Longitude") + ylab("Latitude") +
  annotation_scale(location = "br", width_hint = 0.1, line_width = 0.1, bar_cols = c("grey28","white")) +
  annotation_north_arrow(location = "br", which_north = "true", 
                         pad_x = unit(1.5, "cm"), pad_y = unit(1, "cm"),
                         style = north_arrow_fancy_orienteering(fill = c("white", "grey28")))

```
<!-- </div> -->

```{r FINAL MERGED DFs AND TABLE PLOT}
#--------------------------------------------------------
#-MERGE wbank_inform_combi and adm_country stats dfs
#-------------------------------------------------------
all<-plyr::rbind.fill(Wbank_inform_combi,adm_country) %>%
  mutate(URL =paste0("[",URL, "](", URL, ")")) %>%
  mutate(Unit = case_when(grepl("scale|count|RP|=|constant|aggregate", Unit) ==FALSE ~ gsub("[()]", "", Unit),
            TRUE ~ Unit)) %>%
  mutate(Description = as.character(paste0("The ", tolower(Index_name)," for ", country_full," is estimated to be ",
                                           Value," ",Unit,", which is considered ", tolower(`Comparative Value`)," value as compared to ",
                                           Rank_out_of," other countries. Additionally, ",country_full," ranks at ",Rank," out of ",Rank_out_of,
                                           " around the world. These estimates were taken from ",Source,", made in ",`Year of Publication`,". (", URL,")"))) %>%
  rename(Name = Index_name) %>%
  arrange(factor(Category, levels = target_grp), Name) %>%
  filter(!grepl("HA",Index)) %>% #some step to clean...
    filter(complete.cases(.)) #remove columns that contains Any NA. - complete.cases

#table big
all[c(5,10,11)] %>%
  kbl(escape=F, align = 'rcl') %>%
  #kable_paper(full_width = T, font_size = 14) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"),full_width = T, font_size = 14) %>%
  column_spec(1, width = "5em", border_right = T, extra_css = "vertical-align:middle;") %>%
  column_spec(2,width = "3em", color = "white", extra_css = "vertical-align:middle;",
              background = spec_color(as.numeric(all$`Comparative Value`),alpha = 0.5, end = 0.4, option = "inferno"))%>%
  column_spec(3, width = "60em")%>%
  pack_rows(index = table(fct_inorder(all$Category)), hline_before = T, bold=T) 

```



